apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}
  labels: {{ include "common.labels" . | indent 4 }}
spec:
  selector:
    matchLabels: {{ include "common.labels" . | indent 6 }}
  replicas: 3
  template:
    metadata:
      labels: {{ include "common.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.port }}