# Default values for mynginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

port: 80

image: nginx:latest

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  name: nginx-clus-port
